# Use the Node.js 20.14.0 base image
FROM node:20.14.0

# Create and set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files to the working directory
COPY . .

# Start the application
CMD ["node", "token-manager.js"]